title: "Repositorio"
author: "Diego Cabrera"
description: "este es un blog que debería ser un blog y un blog"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  #- {file: "index.html", title: "Cosas que escribo"}
  #- {file: "README.md", title: "Acerca de mí"}
  #- {title: "ssisis", file: "/cosas.md"}
  - {file : "pagina1.md", title: "pagina 1 prueba"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:diego.cabrera.o@usach.cl"}
  - {title: Github, icon: github, url: "https://github.com/diego-c-o"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
